name: pytest-ansible-vagrant
description: pytest plugin for testing ansible roles against VMs with vagrant and returning a pytest-testinfra `host` object

license: apache

github:
  visibility: public
