"""Type stubs for testinfra Host and modules.

testinfra doesn't ship with py.typed, so we define Protocol classes
for IDE autocompletion and type checking.
"""

from __future__ import annotations

import datetime
from typing import Any, Iterator, Protocol


class CommandResultProtocol(Protocol):
    @property
    def rc(self) -> int: ...
    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...
    @property
    def command(self) -> str: ...
    @property
    def succeeded(self) -> bool: ...
    @property
    def failed(self) -> bool: ...


class FileProtocol(Protocol):
    @property
    def exists(self) -> bool: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def is_directory(self) -> bool: ...
    @property
    def is_symlink(self) -> bool: ...
    @property
    def is_pipe(self) -> bool: ...
    @property
    def is_socket(self) -> bool: ...
    @property
    def linked_to(self) -> str: ...
    @property
    def user(self) -> str: ...
    @property
    def uid(self) -> int: ...
    @property
    def group(self) -> str: ...
    @property
    def gid(self) -> int: ...
    @property
    def mode(self) -> int: ...
    @property
    def content(self) -> bytes: ...
    @property
    def content_string(self) -> str: ...
    @property
    def mtime(self) -> datetime.datetime: ...
    @property
    def size(self) -> int: ...
    @property
    def md5sum(self) -> str: ...
    @property
    def sha256sum(self) -> str: ...
    def contains(self, pattern: str) -> bool: ...
    def listdir(self) -> list[str]: ...


class PackageProtocol(Protocol):
    @property
    def is_installed(self) -> bool: ...
    @property
    def version(self) -> str: ...
    @property
    def release(self) -> str: ...


class ServiceProtocol(Protocol):
    @property
    def is_running(self) -> bool: ...
    @property
    def is_enabled(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def is_masked(self) -> bool: ...
    @property
    def systemd_properties(self) -> dict[str, str]: ...


class SocketProtocol(Protocol):
    @property
    def is_listening(self) -> bool: ...
    @property
    def clients(self) -> list[tuple[str, int]]: ...


class UserProtocol(Protocol):
    @property
    def exists(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def uid(self) -> int: ...
    @property
    def gid(self) -> int: ...
    @property
    def group(self) -> str: ...
    @property
    def groups(self) -> list[str]: ...
    @property
    def home(self) -> str: ...
    @property
    def shell(self) -> str: ...
    @property
    def password(self) -> str: ...
    @property
    def expiration_date(self) -> datetime.datetime | None: ...


class GroupProtocol(Protocol):
    @property
    def exists(self) -> bool: ...
    @property
    def gid(self) -> int: ...
    @property
    def members(self) -> list[str]: ...


class ProcessProtocol(Protocol):
    @property
    def pid(self) -> int: ...
    @property
    def ppid(self) -> int: ...
    @property
    def user(self) -> str: ...
    @property
    def group(self) -> str: ...
    @property
    def nlwp(self) -> int: ...
    @property
    def comm(self) -> str: ...
    @property
    def args(self) -> str: ...
    @property
    def pmem(self) -> float: ...
    @property
    def pcpu(self) -> float: ...


class ProcessFilterProtocol(Protocol):
    def __iter__(self) -> Iterator[ProcessProtocol]: ...
    def __len__(self) -> int: ...


class AddrProtocol(Protocol):
    @property
    def is_reachable(self) -> bool: ...
    @property
    def is_resolvable(self) -> bool: ...
    @property
    def ipv4_addresses(self) -> list[str]: ...
    @property
    def ipv6_addresses(self) -> list[str]: ...
    def port(self, port: int) -> AddrPortProtocol: ...


class AddrPortProtocol(Protocol):
    @property
    def is_reachable(self) -> bool: ...


class InterfaceProtocol(Protocol):
    @property
    def exists(self) -> bool: ...
    @property
    def speed(self) -> int: ...
    @property
    def addresses(self) -> list[str]: ...
    @property
    def link(self) -> dict[str, Any]: ...


class MountPointProtocol(Protocol):
    @property
    def exists(self) -> bool: ...
    @property
    def filesystem(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def options(self) -> list[str]: ...


class SysctlProtocol(Protocol):
    def __call__(self, name: str) -> str | int: ...


class SystemInfoProtocol(Protocol):
    @property
    def type(self) -> str: ...
    @property
    def distribution(self) -> str: ...
    @property
    def release(self) -> str: ...
    @property
    def codename(self) -> str: ...
    @property
    def arch(self) -> str: ...
    @property
    def hostname(self) -> str: ...


class SudoProtocol(Protocol):
    def __call__(self, user: str | None = None) -> SudoContextProtocol: ...


class SudoContextProtocol(Protocol):
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...


class PipProtocol(Protocol):
    @property
    def is_installed(self) -> bool: ...
    @property
    def version(self) -> str: ...
    @classmethod
    def check(cls, pip_path: str = "pip") -> CommandResultProtocol: ...


class EnvironmentProtocol(Protocol):
    def __call__(self) -> dict[str, str]: ...


class AnsibleProtocol(Protocol):
    def __call__(
        self, module: str, params: str | None = None, check: bool = True
    ) -> dict[str, Any]: ...
    def get_variables(self) -> dict[str, Any]: ...


class HostProtocol(Protocol):
    """Protocol for testinfra Host class."""

    def file(self, path: str) -> FileProtocol: ...
    def package(self, name: str) -> PackageProtocol: ...
    def service(self, name: str) -> ServiceProtocol: ...
    def socket(self, spec: str) -> SocketProtocol: ...
    def user(self, name: str) -> UserProtocol: ...
    def group(self, name: str) -> GroupProtocol: ...
    def process(self) -> ProcessFilterProtocol: ...
    def addr(self, address: str) -> AddrProtocol: ...
    def interface(self, name: str) -> InterfaceProtocol: ...
    def mount_point(self, path: str) -> MountPointProtocol: ...
    def pip(self, name: str, pip_path: str = "pip") -> PipProtocol: ...
    def run(self, command: str, *args: str) -> CommandResultProtocol: ...
    def run_expect(
        self, expected: list[int], command: str, *args: str
    ) -> CommandResultProtocol: ...
    def run_test(self, command: str, *args: str) -> CommandResultProtocol: ...
    def check_output(self, command: str, *args: str) -> str: ...
    def exists(self, command: str) -> bool: ...
    def find_command(
        self, command: str, extrapaths: tuple[str, ...] = ("/sbin", "/usr/sbin")
    ) -> str: ...

    @property
    def sysctl(self) -> SysctlProtocol: ...
    @property
    def system_info(self) -> SystemInfoProtocol: ...
    @property
    def sudo(self) -> SudoProtocol: ...
    @property
    def environment(self) -> EnvironmentProtocol: ...
    @property
    def ansible(self) -> AnsibleProtocol: ...
